apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    basicAuthUser: kiva_admin
    jsonData:
      addCorsHeader: true
      defaultDatabase: analytics
      user: kiva_admin
      username: kiva_admin
      password: kiva_password
    secureJsonData:
      basicAuthPassword: kiva_password
      password: kiva_password
    editable: true
